apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: ispersonoppgave-alerts
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#syfo-alarm'
      prependText: '<!here> | '
  alerts:
    - alert: ISPERSONOPPGAVE IS DOWN(PROD)
      expr: count(kube_pod_container_status_running{container="ispersonoppgave"}) == 0
      for: 5m
      description: "Det er ingen pods for app kjørende i namespace og dermed er appen nede"
      action: "Undersøk hvofor pods er nede og få den kjørende igjen!"
      severity: danger
    - alert: ISPERSONOPPGAVE is restarting alot(PROD)
      expr: sum(increase(kube_pod_container_status_restarts_total{container="ispersonoppgave"}[1h])) > 5
      for: 10m
      description: "App restarter mange ganger"
      action: "Undersøk hvorfor pods restarter ofte."
      severity: warning
