apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispersonoppgave
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /is_ready
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  leaderElection: true
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://ispersonoppgave.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      external:
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: syfo-tilgangskontroll
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: ispersonoppgave-db
        diskAutoresize: true
  envFrom:
    - secret: ispersonoppgave-serviceuser
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: production
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "http://syfo-tilgangskontroll"
    - name: OUTDATED_DIALOGMOTESVAR_CUTOFF
      value: "2022-04-01"
    - name: TOGGLE_KAFKA_CONSUMER_AKTIVITETSKRAV_EXPIRED_VARSEL
      value: "false"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: IS_AKTIVITETSKRAV_VURDERING_CONSUMER_ENABLED
      value: "false"
