apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispersonoppgave
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /is_ready
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  leaderElection: true
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://ispersonoppgave.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
    outbound:
      external:
        - host: "kafka-schema-registry.nais-q.adeo.no"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: ispersonoppgave-db
        diskAutoresize: true
  envFrom:
    - secret: ispersonoppgave-serviceuser
  kafka:
    pool: nav-dev
  env:
    - name: KTOR_ENV
      value: production
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
    - name: TOGGLE_KAFKA_STATUSENDRING_CONSUMER_ENABLED
      value: "true"
    - name: TOGGLE_KAFKA_DIALOGMOTESVAR_CONSUMER_ENABLED
      value: "true"
    - name: PUBLISH_OPPGAVEHENDELSER_ENABLED
      value: "true"
    - name: OUTDATED_DIALOGMOTESVAR_CUTOFF
      value: "2022-04-01"
    - name: TOGGLE_KAFKA_IDENTHENDELSE_CONSUMER_ENABLED
      value: "true"
