apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispersonoppgave
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://ispersonoppgave.nais.preprod.local"
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvispersonoppgave
        mountPath: /secrets/serviceuser
  webproxy: true
  env:
    - name: KTOR_ENV
      value: production
    - name: LOGINSERVICE_CLIENT_ID
      value: 38e07d31-659d-4595-939a-f18dce3446c5
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: ISPERSONOPPGAVE_DB_URL
      value: jdbc:postgresql://b27dbvl022.preprod.local:5432/ispersonoppgave
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: "https://security-token-service.nais.preprod.local"
    - name: SYFOBEHANDLENDEENHET_URL
      value: https://syfobehandlendeenhet.nais.preprod.local
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.nais.preprod.local"
