apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ispersonoppgave
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 768Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://ispersonoppgave.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://ispersonoppgave.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvispersonoppgave
        mountPath: /secrets/serviceuser
  webproxy: true
  env:
    - name: KTOR_ENV
      value: production
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: ISPERSONOPPGAVE_DB_URL
      value: jdbc:postgresql://b27dbvl022.preprod.local:5432/ispersonoppgave
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.dev.intern.nav.no"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.nais.preprod.local"
