package no.nav.syfo.personoppgavehendelse.domain

enum class PersonoppgavehendelseType {
    OPPFOLGINGSPLANLPS_BISTAND_MOTTATT,
    OPPFOLGINGSPLANLPS_BISTAND_BEHANDLET,
    DIALOGMOTESVAR_MOTTATT,
    DIALOGMOTESVAR_BEHANDLET,
    MOTEBEHOV_SVAR_MOTTATT,
    MOTEBEHOV_SVAR_BEHANDLET,
    BEHANDLERDIALOG_SVAR_MOTTATT,
    BEHANDLERDIALOG_SVAR_BEHANDLET,
    BEHANDLERDIALOG_UBESVART_MELDING_MOTTATT,
    BEHANDLERDIALOG_UBESVART_MELDING_BEHANDLET,
}
