package no.nav.syfo.personoppgavehendelse.domain

enum class PersonoppgavehendelseType {
    OPPFOLGINGSPLANLPS_BISTAND_MOTTATT,
    OPPFOLGINGSPLANLPS_BISTAND_BEHANDLET,
    DIALOGMOTESVAR_MOTTATT,
    DIALOGMOTESVAR_BEHANDLET,
    MOTEBEHOV_SVAR_MOTTATT,
}
