package no.nav.syfo.personoppgave.domain

enum class PersonOppgaveType {
    OPPFOLGINGSPLANLPS,
    DIALOGMOTESVAR,
    BEHANDLERDIALOG_SVAR,
    BEHANDLERDIALOG_MELDING_UBESVART,
    BEHANDLERDIALOG_MELDING_AVVIST,
    AKTIVITETSKRAV_VURDER_STANS,
    BEHANDLER_BER_OM_BISTAND,
}
